name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Tag'
        type: string
  
permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: Install
      run: yarn
    - name: Unit tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
    - name: Publish Test Results
      # You may pin to the exact commit or the version.
      # uses: EnricoMi/publish-unit-test-result-action@27d65e188ec43221b20d26de30f4892fad91df2f
      uses: EnricoMi/publish-unit-test-result-action@v2.22.0
      with:
          files: '**/reports/*.xml' # optional
    - name: Tag commit with version
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        VERSION="v${{ github.event.inputs.version }}"

        git tag -a "$VERSION" -m "Release $VERSION"
        git push origin "$VERSION"
